CREATE SEQUENCE IF NOT EXISTS locations_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS users (
                       id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       login VARCHAR(15) NOT NULL UNIQUE,
                       password VARCHAR(70) NOT NULL
);


CREATE TABLE IF NOT EXISTS locations (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(20),
                        userid INT REFERENCES users(id),
                        latitude NUMERIC,
                        longitude NUMERIC
);

CREATE TABLE IF NOT EXISTS session (
                        id UUID PRIMARY KEY,
                        userid INT REFERENCES users(id),
                        expiresat timestamp
);